<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
<script>
    /*
     1.函数
     async function get(user){    或者  let get = async function（user）{}
         return await ajax();
     }
    
    get(user).then()
   
    
    2. 对象
    let hd = {
        async get(name){
            return await ajax()
        }
    }

    hd.get('name').then()


    3.class

    class cGet{
        async get(name){
            return await ajax()
        }
    }
    new cGet().get('name').then()
    */

    /* 错误处理 */

    /* async 和 await 发生错误时 都可以  交给 .catch() 这个歌错误api进行处理，放在链式最后即可 */

    /* 
     */
    
     try{
        /* 这里发生致命错误了  但是只要捕获处理了，下面的接着的代码还可以正常执行 就相当于小孩子犯错 ，知错能改，就是好的 */
     }catch(error){

     }//如果发生错误不处理，不改正，那么下面的代码不会继续执行！！！

   
</script>
</html>